apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-portfolio-webapp
  namespace: personal-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: personal-portoflio-site
        image: app-prod