name: personal-portfolio-CI

on:
  push:
   branches:
     - main

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-west1
  SERVICE_NAME: personal-portfolio

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
        export_default_credentials: true


    # Build Container Image
    - name: Build
      run: docker-compose -f docker-compose.prod.yml -t $IMAGE_NAME:latest 

    # Configure docker client
    - name: Confgure Docker client
      run: |-
        gcloud auth configure-docker --quiet 
    
    #Push docker image to GCR
    - name: Push Docker Image to GCR
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest us-us-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-us-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push us-us-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push us-us-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG



    
  