name: personal-portfolio-CI

on:
  push:
   branches:
     - main


env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # deploy to GCR
 
    - uses: RafikFarhad/push-to-gcr-github-action@v4
      with:
        gcloud_service_key: ${{ secrets.RUN_SA_KEY }}'
        registry: gcr.io
        project_id: ${{ secrets.RUN_PROJECT }}
        image_name: app-prod
